# Stage 1: Build Stage
FROM node:20-alpine as build-stage
WORKDIR /app

# Dependencies installieren
COPY package*.json ./
RUN npm install

# Quellcode kopieren
COPY . .

# Production Build erstellen
RUN npm run build --no-cache

# Stage 2: Nginx-Server Stage
FROM nginx:alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Nginx-Config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]