version: '3.9'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: getintomealprep_api
    working_dir: /app
    command: sh -c "dotnet watch run --urls=http://0.0.0.0:5000"


    volumes:
      - ./GetIntoMealPrepAPI:/app
    expose:
      - "5000"  # Port nur im internen Docker-Netzwerk sichtbar
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=GetIntoMealPrepDb;Username=postgres;Password=tzutzu123
    depends_on:
      - db

  frontend:
    image: node:20
    container_name: getintomealprep_frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
      - NODE_ENV=development
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: getintomealprep_db
    environment:
      POSTGRES_DB: GetIntoMealPrepDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tzutzu123
    ports:
      - "5433:5432"  # HostPort:ContainerPort
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: getintomealprep_nginx
    ports:
      - "80:80"  # öffentlich sichtbarer Port
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - frontend

volumes:
  pgdata:
